name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout code

    - uses: docker/login-action@v3
    - name: Login to Docker Hub
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image for auch
      run: |
          docker pull dredfort/auth:latest || true
          docker build -t dredfort/auth:latest .
          docker push dredfort/auth:latest
